Awakened King DLC Items
Razzmatazzz/RemnantSaveGuardian pull request #182
Opened 2023-11-15 21:30 UTC by aescolastico

Apologies if this already being worked on. Tried getting the ball rolling on new DLC.

That being said, Im clearly missing something or Im defining the objects incorrectly in the game.json file. The save files are riddled with binary noise so its hard to read them. 
 
Either way, the items I added are not appearing as missing.

2023-11-16 18:31 UTC, dyfrgi requested changes
Thanks for writing this! I think that there are some more items known now as well, take a look at https://www.reddit.com/r/remnantgame/comments/17w04g7/awakened_king_dlc_item_list_as_of_now/.

I figured out why it's not working, it's due to JSON types. If you look at the in-program log when running it you can see the error message, though unfortunately it doesn't include the context of where it is in the JSON.

2023-11-16 18:31 UTC, dyfrgi commented on RemnantSaveGuardian/game.json
> +      "Weapon_AbyssalHook": {
Wrong type here - this should be an array of objects, like you did for Wood Ring.

2023-11-16 19:26 UTC, MrWastedPanic commented
I have been writing down the items I have come across. Once this is committed I can pull and add them or if you want, I can send them to you some other way.

2023-11-16 23:01 UTC, aescolastico commented on RemnantSaveGuardian/game.json
> +          "notes": "Rewarded by killing the Red Prince with the 'Assassin's Dagger' melee weapon.",
agreed

2023-11-16 23:01 UTC, aescolastico commented on RemnantSaveGuardian/game.json
> +          "armorSet": false
agreed

2023-11-17 00:04 UTC, aescolastico commented
> Thanks for writing this! I think that there are some more items known now as well, take a look at https://www.reddit.com/r/remnantgame/comments/17w04g7/awakened_king_dlc_item_list_as_of_now/.

while this list is awesome. we kind of need the gamestrings otherwise wed be guessing at what the devs named these items in the game files. which is sometimes is easy to do if you have the in-game names, but id prefer to be confident about what were proposing for this project. if someone with all these items provides their profile.sav, we could extract these strings.

2023-11-17 00:24 UTC, MrWastedPanic commented
> while this list is awesome. we kind of need the gamestrings otherwise wed be guessing at what the devs named these items in the game files. which is sometimes is easy to do if you have the in-game names, but id prefer to be confident about what were proposing for this project. if someone with all these items provides their profile.sav, we could extract these strings.

I have a large number of these items in my inventory if you want my profile.sav let me know

2023-11-17 00:59 UTC, aescolastico commented
> > while this list is awesome. we kind of need the gamestrings otherwise wed be guessing at what the devs named these items in the game files. which is sometimes is easy to do if you have the in-game names, but id prefer to be confident about what were proposing for this project. if someone with all these items provides their profile.sav, we could extract these strings.
> 
> I have a large number of these items in my inventory if you want my profile.sav let me know

yes that would be helpful

2023-11-17 01:20 UTC, MrWastedPanic commented
> > > while this list is awesome. we kind of need the gamestrings otherwise wed be guessing at what the devs named these items in the game files. which is sometimes is easy to do if you have the in-game names, but id prefer to be confident about what were proposing for this project. if someone with all these items provides their profile.sav, we could extract these strings.
> > 
> > 
> > I have a large number of these items in my inventory if you want my profile.sav let me know
> 
> yes that would be helpful

Let me know how I can send it to you and it's yours

2023-11-17 01:45 UTC, aescolastico commented
@MrWastedPanic you can just attach the file to a comment in this very thread.

2023-11-17 02:25 UTC, MrWastedPanic commented
> @MrWastedPanic you can just attach the file to a comment in this very thread.

Let me know if that worked for you

[profile.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/13386357/profile.zip)

2023-11-17 20:10 UTC, MrWastedPanic commented on RemnantSaveGuardian/game.json
> +          "armorSet": false
Maybe revert the whitespace changes till after the DLC piece is added (or at least the known pieces) so we can get this merged and continue working?

2023-11-17 20:13 UTC, MrWastedPanic commented on RemnantSaveGuardian/game.json
> +          "name": "/Items/Trinkets/Rings/BrightSteelRing/Ring_BrightSteelRing",
Again, maybe wrap this change to the whitespace changes mentioned above and call it a QoL update after the DLC information?

2023-11-22 00:41 UTC, aescolastico commented
I'll have to check, but i think PR#193 covers all these changes and more, so i can probably just close this PR.

2023-11-22 14:23 UTC, Razzmatazzz commented
@aescolastico there were three competing PRs for the DLC items, but two of them (including this one) were marked as drafts so I merged the one that was marked as ready. For future PRs, be sure to mark them as ready when they're ready so I know it's time to review and I can get them merged.

2024-01-23 23:27 UTC, closed without merging